# https://www.home-assistant.io/integrations/default_config/
default_config:

oref_alert:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.oref_alert: debug