name: "Manifest"

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * *"

jobs:
  metadata:
    name: "Manifest libraries update"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.1.7"

        - name: "Set up Python"
          uses: actions/setup-python@v5.1.1
          with:
            python-version: "3.12"
            cache: "pip"

        - name: "Update manifest file"
          shell: "bash"
          run: scripts/update_manifest.py

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v6.1.0
          with:
            title: Manifest libraries update
            body: Automated changes by "Manifest" GitHub action
            commit-message: Manifest update
