name: "Manifest"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "requirements.txt"
      - "custom_components/oref_alert/manifest.json"
jobs:
  metadata:
    name: "Manifest libraries update"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.2.2"

        - name: "Set up Python"
          uses: actions/setup-python@v5.4.0
          with:
            python-version: "3.13"
            cache: "pip"

        - name: "Update manifest file"
          shell: "bash"
          run: scripts/update_manifest.py

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v7.0.8
          id: pr
          with:
            token: ${{ secrets.MANIFEST_GITHUB_TOKEN }}
            branch: create-pull-request/manifest
            title: Manifest libraries update
            body: Automated changes by "Manifest" GitHub action
            commit-message: Manifest update

        - name: Enable auto-merge
          if: ${{ steps.pr.outputs.pull-request-number }}
          run: gh pr merge --auto --merge ${{ steps.pr.outputs.pull-request-number }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}